<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ModularAssemblies</RootNamespace>
    <TargetFramework>net48</TargetFramework>
    <Platforms>x64</Platforms>
    <LangVersion>6</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateNeutralResourcesLanguageAttribute>false</GenerateNeutralResourcesLanguageAttribute>
	  <SpaceEngineersBinCopyLocal>true</SpaceEngineersBinCopyLocal>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Data\Scripts\ModularAssemblies\ProductionDefinition.cs" />
    <None Include="Data\Scripts\ModularAssemblies\Production\ProductionManager.cs" />
    <None Include="Data\Scripts\ModularAssemblies\Production\ProductionSystem.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Mal.Mdk2.ModAnalyzers" Version="*" />
    <PackageReference Include="Mal.Mdk2.References" Version="*" />
  </ItemGroup>

  <ItemGroup>
	<Reference Include="Sandbox.Game.dll">
		<HintPath>D:\SteamLibrary\steamapps\common\SpaceEngineers\Bin64\Sandbox.Game.dll</HintPath>
	</Reference>
	<Reference Include="Sandbox.Common.dll">
		<HintPath>D:\SteamLibrary\steamapps\common\SpaceEngineers\Bin64\Sandbox.Common.dll</HintPath>
	</Reference>
	<Reference Include="VRage.Game.dll">
		<HintPath>D:\SteamLibrary\steamapps\common\SpaceEngineers\Bin64)\VRage.Game.dll</HintPath>
	</Reference>
	<Reference Include="VRage.Library.dll">
		<HintPath>D:\SteamLibrary\steamapps\common\SpaceEngineers\Bin64\VRage.Library.dll</HintPath>
	</Reference>
	<Reference Include="VRage.Math.dll">
		<HintPath>D:\SteamLibrary\steamapps\common\SpaceEngineers\Bin64\VRage.Math.dll</HintPath>
	</Reference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Images\" />
  </ItemGroup>

</Project>